const upazilla = [
  {
    id: "1",
    district_id: "1",
    name: "Debidwar Upazila",
    bn_name: "দেবিদ্বার",
    url: "debidwar.comilla.gov.bd",
  },
  {
    id: "2",
    district_id: "1",
    name: "Barura Upazila",
    bn_name: "বরুড়া",
    url: "barura.comilla.gov.bd",
  },
  {
    id: "3",
    district_id: "1",
    name: "Brahmanpara Upazila",
    bn_name: "ব্রাহ্মণপাড়া",
    url: "brahmanpara.comilla.gov.bd",
  },
  {
    id: "4",
    district_id: "1",
    name: "Chandina Upazila",
    bn_name: "চান্দিনা",
    url: "chandina.comilla.gov.bd",
  },
  {
    id: "5",
    district_id: "1",
    name: "Chauddagram Upazila",
    bn_name: "চৌদ্দগ্রাম",
    url: "chauddagram.comilla.gov.bd",
  },
  {
    id: "6",
    district_id: "1",
    name: "Daudkandi Upazila",
    bn_name: "দাউদকান্দি",
    url: "daudkandi.comilla.gov.bd",
  },
  {
    id: "7",
    district_id: "1",
    name: "Homna Upazila",
    bn_name: "হোমনা",
    url: "homna.comilla.gov.bd",
  },
  {
    id: "8",
    district_id: "1",
    name: "Laksam Upazila",
    bn_name: "লাকসাম",
    url: "laksam.comilla.gov.bd",
  },
  {
    id: "9",
    district_id: "1",
    name: "Muradnagar Upazila",
    bn_name: "মুরাদনগর",
    url: "muradnagar.comilla.gov.bd",
  },
  {
    id: "10",
    district_id: "1",
    name: "Nangalkot Upazila",
    bn_name: "নাঙ্গলকোট",
    url: "nangalkot.comilla.gov.bd",
  },
  {
    id: "11",
    district_id: "1",
    name: "Comilla Sadar Upazila",
    bn_name: "কুমিল্লা সদর",
    url: "comillasadar.comilla.gov.bd",
  },
  {
    id: "12",
    district_id: "1",
    name: "Meghna Upazila",
    bn_name: "মেঘনা",
    url: "meghna.comilla.gov.bd",
  },
  {
    id: "13",
    district_id: "1",
    name: "Monohargonj Upazila",
    bn_name: "মনোহরগঞ্জ",
    url: "monohargonj.comilla.gov.bd",
  },
  {
    id: "14",
    district_id: "1",
    name: "Sadarsouth Upazila",
    bn_name: "সদর দক্ষিণ",
    url: "sadarsouth.comilla.gov.bd",
  },
  {
    id: "15",
    district_id: "1",
    name: "Titas Upazila",
    bn_name: "তিতাস",
    url: "titas.comilla.gov.bd",
  },
  {
    id: "16",
    district_id: "1",
    name: "Burichang Upazila",
    bn_name: "বুড়িচং",
    url: "burichang.comilla.gov.bd",
  },
  {
    id: "17",
    district_id: "1",
    name: "Lalmai Upazila",
    bn_name: "লালমাই",
    url: "lalmai.comilla.gov.bd",
  },
  {
    id: "18",
    district_id: "2",
    name: "Chhagalnaiya Upazila",
    bn_name: "ছাগলনাইয়া",
    url: "chhagalnaiya.feni.gov.bd",
  },
  {
    id: "19",
    district_id: "2",
    name: "Feni Sadar Upazila",
    bn_name: "ফেনী সদর",
    url: "sadar.feni.gov.bd",
  },
  {
    id: "20",
    district_id: "2",
    name: "Sonagazi Upazila",
    bn_name: "সোনাগাজী",
    url: "sonagazi.feni.gov.bd",
  },
  {
    id: "21",
    district_id: "2",
    name: "Fulgazi Upazila",
    bn_name: "ফুলগাজী",
    url: "fulgazi.feni.gov.bd",
  },
  {
    id: "22",
    district_id: "2",
    name: "Parshuram Upazila",
    bn_name: "পরশুরাম",
    url: "parshuram.feni.gov.bd",
  },
  {
    id: "23",
    district_id: "2",
    name: "Daganbhuiyan Upazila",
    bn_name: "দাগনভূঞা",
    url: "daganbhuiyan.feni.gov.bd",
  },
  {
    id: "24",
    district_id: "3",
    name: "Brahmanbaria Sadar Upazila",
    bn_name: "ব্রাহ্মণবাড়িয়া সদর",
    url: "sadar.brahmanbaria.gov.bd",
  },
  {
    id: "25",
    district_id: "3",
    name: "Kasba Upazila",
    bn_name: "কসবা",
    url: "kasba.brahmanbaria.gov.bd",
  },
  {
    id: "26",
    district_id: "3",
    name: "Nasirnagar Upazila",
    bn_name: "নাসিরনগর",
    url: "nasirnagar.brahmanbaria.gov.bd",
  },
  {
    id: "27",
    district_id: "3",
    name: "Sarail Upazila",
    bn_name: "সরাইল",
    url: "sarail.brahmanbaria.gov.bd",
  },
  {
    id: "28",
    district_id: "3",
    name: "Ashuganj Upazila",
    bn_name: "আশুগঞ্জ",
    url: "ashuganj.brahmanbaria.gov.bd",
  },
  {
    id: "29",
    district_id: "3",
    name: "Akhaura Upazila",
    bn_name: "আখাউড়া",
    url: "akhaura.brahmanbaria.gov.bd",
  },
  {
    id: "30",
    district_id: "3",
    name: "Nabinagar Upazila",
    bn_name: "নবীনগর",
    url: "nabinagar.brahmanbaria.gov.bd",
  },
  {
    id: "31",
    district_id: "3",
    name: "Bancharampur Upazila",
    bn_name: "বাঞ্ছারামপুর",
    url: "bancharampur.brahmanbaria.gov.bd",
  },
  {
    id: "32",
    district_id: "3",
    name: "Bijoynagar Upazila",
    bn_name: "বিজয়নগর",
    url: "bijoynagar.brahmanbaria.gov.bd    ",
  },
  {
    id: "33",
    district_id: "4",
    name: "Rangamati Sadar Upazila",
    bn_name: "রাঙ্গামাটি সদর",
    url: "sadar.rangamati.gov.bd",
  },
  {
    id: "34",
    district_id: "4",
    name: "Kaptai Upazila",
    bn_name: "কাপ্তাই",
    url: "kaptai.rangamati.gov.bd",
  },
  {
    id: "35",
    district_id: "4",
    name: "Kawkhali Upazila",
    bn_name: "কাউখালী",
    url: "kawkhali.rangamati.gov.bd",
  },
  {
    id: "36",
    district_id: "4",
    name: "Baghaichari Upazila",
    bn_name: "বাঘাইছড়ি",
    url: "baghaichari.rangamati.gov.bd",
  },
  {
    id: "37",
    district_id: "4",
    name: "Barkal Upazila",
    bn_name: "বরকল",
    url: "barkal.rangamati.gov.bd",
  },
  {
    id: "38",
    district_id: "4",
    name: "Langadu Upazila",
    bn_name: "লংগদু",
    url: "langadu.rangamati.gov.bd",
  },
  {
    id: "39",
    district_id: "4",
    name: "Rajasthali Upazila",
    bn_name: "রাজস্থলী",
    url: "rajasthali.rangamati.gov.bd",
  },
  {
    id: "40",
    district_id: "4",
    name: "Belaichari Upazila",
    bn_name: "বিলাইছড়ি",
    url: "belaichari.rangamati.gov.bd",
  },
  {
    id: "41",
    district_id: "4",
    name: "Juraichari Upazila",
    bn_name: "জুরাছড়ি",
    url: "juraichari.rangamati.gov.bd",
  },
  {
    id: "42",
    district_id: "4",
    name: "Naniarchar Upazila",
    bn_name: "নানিয়ারচর",
    url: "naniarchar.rangamati.gov.bd",
  },
  {
    id: "43",
    district_id: "5",
    name: "Noakhali Sadar Upazila",
    bn_name: "নোয়াখালী সদর",
    url: "sadar.noakhali.gov.bd",
  },
  {
    id: "44",
    district_id: "5",
    name: "Companiganj Upazila",
    bn_name: "কোম্পানীগঞ্জ",
    url: "companiganj.noakhali.gov.bd",
  },
  {
    id: "45",
    district_id: "5",
    name: "Begumganj Upazila",
    bn_name: "বেগমগঞ্জ",
    url: "begumganj.noakhali.gov.bd",
  },
  {
    id: "46",
    district_id: "5",
    name: "Hatia Upazila",
    bn_name: "হাতিয়া",
    url: "hatia.noakhali.gov.bd",
  },
  {
    id: "47",
    district_id: "5",
    name: "Subarnachar Upazila",
    bn_name: "সুবর্ণচর",
    url: "subarnachar.noakhali.gov.bd",
  },
  {
    id: "48",
    district_id: "5",
    name: "Kabirhat Upazila",
    bn_name: "কবিরহাট",
    url: "kabirhat.noakhali.gov.bd",
  },
  {
    id: "49",
    district_id: "5",
    name: "Senbug Upazila",
    bn_name: "সেনবাগ",
    url: "senbug.noakhali.gov.bd",
  },
  {
    id: "50",
    district_id: "5",
    name: "Chatkhil Upazila",
    bn_name: "চাটখিল",
    url: "chatkhil.noakhali.gov.bd",
  },
  {
    id: "51",
    district_id: "5",
    name: "Sonaimori Upazila",
    bn_name: "সোনাইমুড়ী",
    url: "sonaimori.noakhali.gov.bd",
  },
  {
    id: "52",
    district_id: "6",
    name: "Haimchar Upazila",
    bn_name: "হাইমচর",
    url: "haimchar.chandpur.gov.bd",
  },
  {
    id: "53",
    district_id: "6",
    name: "Kachua Upazila",
    bn_name: "কচুয়া",
    url: "kachua.chandpur.gov.bd",
  },
  {
    id: "54",
    district_id: "6",
    name: "Shahrasti Upazila",
    bn_name: "শাহরাস্তি\t",
    url: "shahrasti.chandpur.gov.bd",
  },
  {
    id: "55",
    district_id: "6",
    name: "Chandpur Sadar Upazila",
    bn_name: "চাঁদপুর সদর",
    url: "sadar.chandpur.gov.bd",
  },
  {
    id: "56",
    district_id: "6",
    name: "Matlab South Upazila",
    bn_name: "মতলব দক্ষিণ",
    url: "matlabsouth.chandpur.gov.bd",
  },
  {
    id: "57",
    district_id: "6",
    name: "Hajiganj Upazila",
    bn_name: "হাজীগঞ্জ",
    url: "hajiganj.chandpur.gov.bd",
  },
  {
    id: "58",
    district_id: "6",
    name: "Matlab North Upazila",
    bn_name: "মতলব উত্তর",
    url: "matlabnorth.chandpur.gov.bd",
  },
  {
    id: "59",
    district_id: "6",
    name: "Faridgonj Upazila",
    bn_name: "ফরিদগঞ্জ",
    url: "faridgonj.chandpur.gov.bd",
  },
  {
    id: "60",
    district_id: "7",
    name: "Lakshmipur Sadar Upazila",
    bn_name: "লক্ষ্মীপুর সদর",
    url: "sadar.lakshmipur.gov.bd",
  },
  {
    id: "61",
    district_id: "7",
    name: "Kamalnagar Upazila",
    bn_name: "কমলনগর",
    url: "kamalnagar.lakshmipur.gov.bd",
  },
  {
    id: "62",
    district_id: "7",
    name: "Raipur Upazila",
    bn_name: "রায়পুর",
    url: "raipur.lakshmipur.gov.bd",
  },
  {
    id: "63",
    district_id: "7",
    name: "Ramgati Upazila",
    bn_name: "রামগতি",
    url: "ramgati.lakshmipur.gov.bd",
  },
  {
    id: "64",
    district_id: "7",
    name: "Ramganj Upazila",
    bn_name: "রামগঞ্জ",
    url: "ramganj.lakshmipur.gov.bd",
  },
  {
    id: "65",
    district_id: "8",
    name: "Rangunia Upazila",
    bn_name: "রাঙ্গুনিয়া",
    url: "rangunia.chittagong.gov.bd",
  },
  {
    id: "66",
    district_id: "8",
    name: "Sitakunda Upazila",
    bn_name: "সীতাকুন্ড",
    url: "sitakunda.chittagong.gov.bd",
  },
  {
    id: "67",
    district_id: "8",
    name: "Mirsharai Upazila",
    bn_name: "মীরসরাই",
    url: "mirsharai.chittagong.gov.bd",
  },
  {
    id: "68",
    district_id: "8",
    name: "Patiya Upazila",
    bn_name: "পটিয়া",
    url: "patiya.chittagong.gov.bd",
  },
  {
    id: "69",
    district_id: "8",
    name: "Sandwip Upazila",
    bn_name: "সন্দ্বীপ",
    url: "sandwip.chittagong.gov.bd",
  },
  {
    id: "70",
    district_id: "8",
    name: "Banshkhali Upazila",
    bn_name: "বাঁশখালী",
    url: "banshkhali.chittagong.gov.bd",
  },
  {
    id: "71",
    district_id: "8",
    name: "Boalkhali Upazila",
    bn_name: "বোয়ালখালী",
    url: "boalkhali.chittagong.gov.bd",
  },
  {
    id: "72",
    district_id: "8",
    name: "Anwara Upazila",
    bn_name: "আনোয়ারা",
    url: "anwara.chittagong.gov.bd",
  },
  {
    id: "73",
    district_id: "8",
    name: "Chandanaish Upazila",
    bn_name: "চন্দনাইশ",
    url: "chandanaish.chittagong.gov.bd",
  },
  {
    id: "74",
    district_id: "8",
    name: "Satkania Upazila",
    bn_name: "সাতকানিয়া",
    url: "satkania.chittagong.gov.bd",
  },
  {
    id: "75",
    district_id: "8",
    name: "Lohagara Upazila",
    bn_name: "লোহাগাড়া",
    url: "lohagara.chittagong.gov.bd",
  },
  {
    id: "76",
    district_id: "8",
    name: "Hathazari Upazila",
    bn_name: "হাটহাজারী",
    url: "hathazari.chittagong.gov.bd",
  },
  {
    id: "77",
    district_id: "8",
    name: "Fatikchhari Upazila",
    bn_name: "ফটিকছড়ি",
    url: "fatikchhari.chittagong.gov.bd",
  },
  {
    id: "78",
    district_id: "8",
    name: "Raozan Upazila",
    bn_name: "রাউজান",
    url: "raozan.chittagong.gov.bd",
  },
  {
    id: "79",
    district_id: "8",
    name: "Karnafuli Upazila",
    bn_name: "কর্ণফুলী",
    url: "karnafuli.chittagong.gov.bd",
  },
  {
    id: "80",
    district_id: "9",
    name: "Coxsbazar Sadar Upazila",
    bn_name: "কক্সবাজার সদর",
    url: "sadar.coxsbazar.gov.bd",
  },
  {
    id: "81",
    district_id: "9",
    name: "Chakaria Upazila",
    bn_name: "চকরিয়া",
    url: "chakaria.coxsbazar.gov.bd",
  },
  {
    id: "82",
    district_id: "9",
    name: "Kutubdia Upazila",
    bn_name: "কুতুবদিয়া",
    url: "kutubdia.coxsbazar.gov.bd",
  },
  {
    id: "83",
    district_id: "9",
    name: "Ukhiya Upazila",
    bn_name: "উখিয়া",
    url: "ukhiya.coxsbazar.gov.bd",
  },
  {
    id: "84",
    district_id: "9",
    name: "Moheshkhali Upazila",
    bn_name: "মহেশখালী",
    url: "moheshkhali.coxsbazar.gov.bd",
  },
  {
    id: "85",
    district_id: "9",
    name: "Pekua Upazila",
    bn_name: "পেকুয়া",
    url: "pekua.coxsbazar.gov.bd",
  },
  {
    id: "86",
    district_id: "9",
    name: "Ramu Upazila",
    bn_name: "রামু",
    url: "ramu.coxsbazar.gov.bd",
  },
  {
    id: "87",
    district_id: "9",
    name: "Teknaf Upazila",
    bn_name: "টেকনাফ",
    url: "teknaf.coxsbazar.gov.bd",
  },
  {
    id: "88",
    district_id: "10",
    name: "Khagrachhari Sadar Upazila",
    bn_name: "খাগড়াছড়ি সদর",
    url: "sadar.khagrachhari.gov.bd",
  },
  {
    id: "89",
    district_id: "10",
    name: "Dighinala Upazila",
    bn_name: "দিঘীনালা",
    url: "dighinala.khagrachhari.gov.bd",
  },
  {
    id: "90",
    district_id: "10",
    name: "Panchari Upazila",
    bn_name: "পানছড়ি",
    url: "panchari.khagrachhari.gov.bd",
  },
  {
    id: "91",
    district_id: "10",
    name: "Laxmichhari Upazila",
    bn_name: "লক্ষীছড়ি",
    url: "laxmichhari.khagrachhari.gov.bd",
  },
  {
    id: "92",
    district_id: "10",
    name: "Mohalchari Upazila",
    bn_name: "মহালছড়ি",
    url: "mohalchari.khagrachhari.gov.bd",
  },
  {
    id: "93",
    district_id: "10",
    name: "Manikchari Upazila",
    bn_name: "মানিকছড়ি",
    url: "manikchari.khagrachhari.gov.bd",
  },
  {
    id: "94",
    district_id: "10",
    name: "Ramgarh Upazila",
    bn_name: "রামগড়",
    url: "ramgarh.khagrachhari.gov.bd",
  },
  {
    id: "95",
    district_id: "10",
    name: "Matiranga Upazila",
    bn_name: "মাটিরাঙ্গা",
    url: "matiranga.khagrachhari.gov.bd",
  },
  {
    id: "96",
    district_id: "10",
    name: "Guimara Upazila",
    bn_name: "গুইমারা",
    url: "guimara.khagrachhari.gov.bd",
  },
  {
    id: "97",
    district_id: "11",
    name: "Bandarban Sadar Upazila",
    bn_name: "বান্দরবান সদর",
    url: "sadar.bandarban.gov.bd",
  },
  {
    id: "98",
    district_id: "11",
    name: "Alikadam Upazila",
    bn_name: "আলীকদম",
    url: "alikadam.bandarban.gov.bd",
  },
  {
    id: "99",
    district_id: "11",
    name: "Naikhongchhari Upazila",
    bn_name: "নাইক্ষ্যংছড়ি",
    url: "naikhongchhari.bandarban.gov.bd",
  },
  {
    id: "100",
    district_id: "11",
    name: "Rowangchhari Upazila",
    bn_name: "রোয়াংছড়ি",
    url: "rowangchhari.bandarban.gov.bd",
  },
  {
    id: "101",
    district_id: "11",
    name: "Lama Upazila",
    bn_name: "লামা",
    url: "lama.bandarban.gov.bd",
  },
  {
    id: "102",
    district_id: "11",
    name: "Ruma Upazila",
    bn_name: "রুমা",
    url: "ruma.bandarban.gov.bd",
  },
  {
    id: "103",
    district_id: "11",
    name: "Thanchi Upazila",
    bn_name: "থানচি",
    url: "thanchi.bandarban.gov.bd",
  },
  {
    id: "104",
    district_id: "12",
    name: "Belkuchi Upazila",
    bn_name: "বেলকুচি",
    url: "belkuchi.sirajganj.gov.bd",
  },
  {
    id: "105",
    district_id: "12",
    name: "Chauhali Upazila",
    bn_name: "চৌহালি",
    url: "chauhali.sirajganj.gov.bd",
  },
  {
    id: "106",
    district_id: "12",
    name: "Kamarkhand Upazila",
    bn_name: "কামারখন্দ",
    url: "kamarkhand.sirajganj.gov.bd",
  },
  {
    id: "107",
    district_id: "12",
    name: "Kazipur Upazila",
    bn_name: "কাজীপুর",
    url: "kazipur.sirajganj.gov.bd",
  },
  {
    id: "108",
    district_id: "12",
    name: "Raigonj Upazila",
    bn_name: "রায়গঞ্জ",
    url: "raigonj.sirajganj.gov.bd",
  },
  {
    id: "109",
    district_id: "12",
    name: "Shahjadpur Upazila",
    bn_name: "শাহজাদপুর",
    url: "shahjadpur.sirajganj.gov.bd",
  },
  {
    id: "110",
    district_id: "12",
    name: "Sirajganj Sadar Upazila",
    bn_name: "সিরাজগঞ্জ সদর",
    url: "sirajganjsadar.sirajganj.gov.bd",
  },
  {
    id: "111",
    district_id: "12",
    name: "Tarash Upazila",
    bn_name: "তাড়াশ",
    url: "tarash.sirajganj.gov.bd",
  },
  {
    id: "112",
    district_id: "12",
    name: "Ullapara Upazila",
    bn_name: "উল্লাপাড়া",
    url: "ullapara.sirajganj.gov.bd",
  },
  {
    id: "113",
    district_id: "13",
    name: "Sujanagar Upazila",
    bn_name: "সুজানগর",
    url: "sujanagar.pabna.gov.bd",
  },
  {
    id: "114",
    district_id: "13",
    name: "Ishurdi Upazila",
    bn_name: "ঈশ্বরদী",
    url: "ishurdi.pabna.gov.bd",
  },
  {
    id: "115",
    district_id: "13",
    name: "Bhangura Upazila",
    bn_name: "ভাঙ্গুড়া",
    url: "bhangura.pabna.gov.bd",
  },
  {
    id: "116",
    district_id: "13",
    name: "Pabna Sadar Upazila",
    bn_name: "পাবনা সদর",
    url: "pabnasadar.pabna.gov.bd",
  },
  {
    id: "117",
    district_id: "13",
    name: "Bera Upazila",
    bn_name: "বেড়া",
    url: "bera.pabna.gov.bd",
  },
  {
    id: "118",
    district_id: "13",
    name: "Atghoria Upazila",
    bn_name: "আটঘরিয়া",
    url: "atghoria.pabna.gov.bd",
  },
  {
    id: "119",
    district_id: "13",
    name: "Chatmohar Upazila",
    bn_name: "চাটমোহর",
    url: "chatmohar.pabna.gov.bd",
  },
  {
    id: "120",
    district_id: "13",
    name: "Santhia Upazila",
    bn_name: "সাঁথিয়া",
    url: "santhia.pabna.gov.bd",
  },
  {
    id: "121",
    district_id: "13",
    name: "Faridpur Upazila",
    bn_name: "ফরিদপুর",
    url: "faridpur.pabna.gov.bd",
  },
  {
    id: "122",
    district_id: "14",
    name: "Kahaloo Upazila",
    bn_name: "কাহালু",
    url: "kahaloo.bogra.gov.bd",
  },
  {
    id: "123",
    district_id: "14",
    name: "Bogra Sadar Upazila",
    bn_name: "বগুড়া সদর",
    url: "sadar.bogra.gov.bd",
  },
  {
    id: "124",
    district_id: "14",
    name: "Shariakandi Upazila",
    bn_name: "সারিয়াকান্দি",
    url: "shariakandi.bogra.gov.bd",
  },
  {
    id: "125",
    district_id: "14",
    name: "Shajahanpur Upazila",
    bn_name: "শাজাহানপুর",
    url: "shajahanpur.bogra.gov.bd",
  },
  {
    id: "126",
    district_id: "14",
    name: "Dupchanchia Upazila",
    bn_name: "দুপচাচিঁয়া",
    url: "dupchanchia.bogra.gov.bd",
  },
  {
    id: "127",
    district_id: "14",
    name: "Adamdighi Upazila",
    bn_name: "আদমদিঘি",
    url: "adamdighi.bogra.gov.bd",
  },
  {
    id: "128",
    district_id: "14",
    name: "Nondigram Upazila",
    bn_name: "নন্দিগ্রাম",
    url: "nondigram.bogra.gov.bd",
  },
  {
    id: "129",
    district_id: "14",
    name: "Sonatala Upazila",
    bn_name: "সোনাতলা",
    url: "sonatala.bogra.gov.bd",
  },
  {
    id: "130",
    district_id: "14",
    name: "Dhunot Upazila",
    bn_name: "ধুনট",
    url: "dhunot.bogra.gov.bd",
  },
  {
    id: "131",
    district_id: "14",
    name: "Gabtali Upazila",
    bn_name: "গাবতলী",
    url: "gabtali.bogra.gov.bd",
  },
  {
    id: "132",
    district_id: "14",
    name: "Sherpur Upazila",
    bn_name: "শেরপুর",
    url: "sherpur.bogra.gov.bd",
  },
  {
    id: "133",
    district_id: "14",
    name: "Shibganj Upazila",
    bn_name: "শিবগঞ্জ",
    url: "shibganj.bogra.gov.bd",
  },
  {
    id: "134",
    district_id: "15",
    name: "Paba Upazila",
    bn_name: "পবা",
    url: "paba.rajshahi.gov.bd",
  },
  {
    id: "135",
    district_id: "15",
    name: "Durgapur Upazila",
    bn_name: "দুর্গাপুর",
    url: "durgapur.rajshahi.gov.bd",
  },
  {
    id: "136",
    district_id: "15",
    name: "Mohonpur Upazila",
    bn_name: "মোহনপুর",
    url: "mohonpur.rajshahi.gov.bd",
  },
  {
    id: "137",
    district_id: "15",
    name: "Charghat Upazila",
    bn_name: "চারঘাট",
    url: "charghat.rajshahi.gov.bd",
  },
  {
    id: "138",
    district_id: "15",
    name: "Puthia Upazila",
    bn_name: "পুঠিয়া",
    url: "puthia.rajshahi.gov.bd",
  },
  {
    id: "139",
    district_id: "15",
    name: "Bagha Upazila",
    bn_name: "বাঘা",
    url: "bagha.rajshahi.gov.bd",
  },
  {
    id: "140",
    district_id: "15",
    name: "Godagari Upazila",
    bn_name: "গোদাগাড়ী",
    url: "godagari.rajshahi.gov.bd",
  },
  {
    id: "141",
    district_id: "15",
    name: "Tanore Upazila",
    bn_name: "তানোর",
    url: "tanore.rajshahi.gov.bd",
  },
  {
    id: "142",
    district_id: "15",
    name: "Bagmara Upazila",
    bn_name: "বাগমারা",
    url: "bagmara.rajshahi.gov.bd",
  },
  {
    id: "143",
    district_id: "16",
    name: "Natore Sadar Upazila",
    bn_name: "নাটোর সদর",
    url: "natoresadar.natore.gov.bd",
  },
  {
    id: "144",
    district_id: "16",
    name: "Singra Upazila",
    bn_name: "সিংড়া",
    url: "singra.natore.gov.bd",
  },
  {
    id: "145",
    district_id: "16",
    name: "Baraigram Upazila",
    bn_name: "বড়াইগ্রাম",
    url: "baraigram.natore.gov.bd",
  },
  {
    id: "146",
    district_id: "16",
    name: "Bagatipara Upazila",
    bn_name: "বাগাতিপাড়া",
    url: "bagatipara.natore.gov.bd",
  },
  {
    id: "147",
    district_id: "16",
    name: "Lalpur Upazila",
    bn_name: "লালপুর",
    url: "lalpur.natore.gov.bd",
  },
  {
    id: "148",
    district_id: "16",
    name: "Gurudaspur Upazila",
    bn_name: "গুরুদাসপুর",
    url: "gurudaspur.natore.gov.bd",
  },
  {
    id: "149",
    district_id: "16",
    name: "Naldanga Upazila",
    bn_name: "নলডাঙ্গা",
    url: "naldanga.natore.gov.bd",
  },
  {
    id: "150",
    district_id: "17",
    name: "Akkelpur Upazila",
    bn_name: "আক্কেলপুর",
    url: "akkelpur.joypurhat.gov.bd",
  },
  {
    id: "151",
    district_id: "17",
    name: "Kalai Upazila",
    bn_name: "কালাই",
    url: "kalai.joypurhat.gov.bd",
  },
  {
    id: "152",
    district_id: "17",
    name: "Khetlal Upazila",
    bn_name: "ক্ষেতলাল",
    url: "khetlal.joypurhat.gov.bd",
  },
  {
    id: "153",
    district_id: "17",
    name: "Panchbibi Upazila",
    bn_name: "পাঁচবিবি",
    url: "panchbibi.joypurhat.gov.bd",
  },
  {
    id: "154",
    district_id: "17",
    name: "Joypurhat Sadar Upazila",
    bn_name: "জয়পুরহাট সদর",
    url: "joypurhatsadar.joypurhat.gov.bd",
  },
  {
    id: "155",
    district_id: "18",
    name: "Chapainawabganj Sadar Upazila",
    bn_name: "চাঁপাইনবাবগঞ্জ সদর",
    url: "chapainawabganjsadar.chapainawabganj.gov.bd",
  },
  {
    id: "156",
    district_id: "18",
    name: "Gomostapur Upazila",
    bn_name: "গোমস্তাপুর",
    url: "gomostapur.chapainawabganj.gov.bd",
  },
  {
    id: "157",
    district_id: "18",
    name: "Nachol Upazila",
    bn_name: "নাচোল",
    url: "nachol.chapainawabganj.gov.bd",
  },
  {
    id: "158",
    district_id: "18",
    name: "Bholahat Upazila",
    bn_name: "ভোলাহাট",
    url: "bholahat.chapainawabganj.gov.bd",
  },
  {
    id: "159",
    district_id: "18",
    name: "Shibganj Upazila",
    bn_name: "শিবগঞ্জ",
    url: "shibganj.chapainawabganj.gov.bd",
  },
  {
    id: "160",
    district_id: "19",
    name: "Mohadevpur Upazila",
    bn_name: "মহাদেবপুর",
    url: "mohadevpur.naogaon.gov.bd",
  },
  {
    id: "161",
    district_id: "19",
    name: "Badalgachi Upazila",
    bn_name: "বদলগাছী",
    url: "badalgachi.naogaon.gov.bd",
  },
  {
    id: "162",
    district_id: "19",
    name: "Patnitala Upazila",
    bn_name: "পত্নিতলা",
    url: "patnitala.naogaon.gov.bd",
  },
  {
    id: "163",
    district_id: "19",
    name: "Dhamoirhat Upazila",
    bn_name: "ধামইরহাট",
    url: "dhamoirhat.naogaon.gov.bd",
  },
  {
    id: "164",
    district_id: "19",
    name: "Niamatpur Upazila",
    bn_name: "নিয়ামতপুর",
    url: "niamatpur.naogaon.gov.bd",
  },
  {
    id: "165",
    district_id: "19",
    name: "Manda Upazila",
    bn_name: "মান্দা",
    url: "manda.naogaon.gov.bd",
  },
  {
    id: "166",
    district_id: "19",
    name: "Atrai Upazila",
    bn_name: "আত্রাই",
    url: "atrai.naogaon.gov.bd",
  },
  {
    id: "167",
    district_id: "19",
    name: "Raninagar Upazila",
    bn_name: "রাণীনগর",
    url: "raninagar.naogaon.gov.bd",
  },
  {
    id: "168",
    district_id: "19",
    name: "Naogaon Sadar Upazila",
    bn_name: "নওগাঁ সদর",
    url: "naogaonsadar.naogaon.gov.bd",
  },
  {
    id: "169",
    district_id: "19",
    name: "Porsha Upazila",
    bn_name: "পোরশা",
    url: "porsha.naogaon.gov.bd",
  },
  {
    id: "170",
    district_id: "19",
    name: "Sapahar Upazila",
    bn_name: "সাপাহার",
    url: "sapahar.naogaon.gov.bd",
  },
  {
    id: "171",
    district_id: "20",
    name: "Manirampur Upazila",
    bn_name: "মণিরামপুর",
    url: "manirampur.jessore.gov.bd",
  },
  {
    id: "172",
    district_id: "20",
    name: "Abhaynagar Upazila",
    bn_name: "অভয়নগর",
    url: "abhaynagar.jessore.gov.bd",
  },
  {
    id: "173",
    district_id: "20",
    name: "Bagherpara Upazila",
    bn_name: "বাঘারপাড়া",
    url: "bagherpara.jessore.gov.bd",
  },
  {
    id: "174",
    district_id: "20",
    name: "Chougachha Upazila",
    bn_name: "চৌগাছা",
    url: "chougachha.jessore.gov.bd",
  },
  {
    id: "175",
    district_id: "20",
    name: "Jhikargacha Upazila",
    bn_name: "ঝিকরগাছা",
    url: "jhikargacha.jessore.gov.bd",
  },
  {
    id: "176",
    district_id: "20",
    name: "Keshabpur Upazila",
    bn_name: "কেশবপুর",
    url: "keshabpur.jessore.gov.bd",
  },
  {
    id: "177",
    district_id: "20",
    name: "Jessore Sadar Upazila",
    bn_name: "যশোর সদর",
    url: "sadar.jessore.gov.bd",
  },
  {
    id: "178",
    district_id: "20",
    name: "Sharsha Upazila",
    bn_name: "শার্শা",
    url: "sharsha.jessore.gov.bd",
  },
  {
    id: "179",
    district_id: "21",
    name: "Assasuni Upazila",
    bn_name: "আশাশুনি",
    url: "assasuni.satkhira.gov.bd",
  },
  {
    id: "180",
    district_id: "21",
    name: "Debhata Upazila",
    bn_name: "দেবহাটা",
    url: "debhata.satkhira.gov.bd",
  },
  {
    id: "181",
    district_id: "21",
    name: "Kalaroa Upazila",
    bn_name: "কলারোয়া",
    url: "kalaroa.satkhira.gov.bd",
  },
  {
    id: "182",
    district_id: "21",
    name: "Satkhira Sadar Upazila",
    bn_name: "সাতক্ষীরা সদর",
    url: "satkhirasadar.satkhira.gov.bd",
  },
  {
    id: "183",
    district_id: "21",
    name: "Shyamnagar Upazila",
    bn_name: "শ্যামনগর",
    url: "shyamnagar.satkhira.gov.bd",
  },
  {
    id: "184",
    district_id: "21",
    name: "Tala Upazila",
    bn_name: "তালা",
    url: "tala.satkhira.gov.bd",
  },
  {
    id: "185",
    district_id: "21",
    name: "Kaliganj Upazila",
    bn_name: "কালিগঞ্জ",
    url: "kaliganj.satkhira.gov.bd",
  },
  {
    id: "186",
    district_id: "22",
    name: "Mujibnagar Upazila",
    bn_name: "মুজিবনগর",
    url: "mujibnagar.meherpur.gov.bd",
  },
  {
    id: "187",
    district_id: "22",
    name: "Meherpur Sadar Upazila",
    bn_name: "মেহেরপুর সদর",
    url: "meherpursadar.meherpur.gov.bd",
  },
  {
    id: "188",
    district_id: "22",
    name: "Gangni Upazila",
    bn_name: "গাংনী",
    url: "gangni.meherpur.gov.bd",
  },
  {
    id: "189",
    district_id: "23",
    name: "Narail Sadar Upazila",
    bn_name: "নড়াইল সদর",
    url: "narailsadar.narail.gov.bd",
  },
  {
    id: "190",
    district_id: "23",
    name: "Lohagara Upazila",
    bn_name: "লোহাগড়া",
    url: "lohagara.narail.gov.bd",
  },
  {
    id: "191",
    district_id: "23",
    name: "Kalia Upazila",
    bn_name: "কালিয়া",
    url: "kalia.narail.gov.bd",
  },
  {
    id: "192",
    district_id: "24",
    name: "Chuadanga Sadar Upazila",
    bn_name: "চুয়াডাঙ্গা সদর",
    url: "chuadangasadar.chuadanga.gov.bd",
  },
  {
    id: "193",
    district_id: "24",
    name: "Alamdanga Upazila",
    bn_name: "আলমডাঙ্গা",
    url: "alamdanga.chuadanga.gov.bd",
  },
  {
    id: "194",
    district_id: "24",
    name: "Damurhuda Upazila",
    bn_name: "দামুড়হুদা",
    url: "damurhuda.chuadanga.gov.bd",
  },
  {
    id: "195",
    district_id: "24",
    name: "Jibannagar Upazila",
    bn_name: "জীবননগর",
    url: "jibannagar.chuadanga.gov.bd",
  },
  {
    id: "196",
    district_id: "25",
    name: "Kushtia Sadar Upazila",
    bn_name: "কুষ্টিয়া সদর",
    url: "kushtiasadar.kushtia.gov.bd",
  },
  {
    id: "197",
    district_id: "25",
    name: "Kumarkhali Upazila",
    bn_name: "কুমারখালী",
    url: "kumarkhali.kushtia.gov.bd",
  },
  {
    id: "198",
    district_id: "25",
    name: "Khoksa Upazila",
    bn_name: "খোকসা",
    url: "khoksa.kushtia.gov.bd",
  },
  {
    id: "199",
    district_id: "25",
    name: "Mirpur Upazila",
    bn_name: "মিরপুর",
    url: "mirpurkushtia.kushtia.gov.bd",
  },
  {
    id: "200",
    district_id: "25",
    name: "Daulatpur Upazila",
    bn_name: "দৌলতপুর",
    url: "daulatpur.kushtia.gov.bd",
  },
  {
    id: "201",
    district_id: "25",
    name: "Bheramara Upazila",
    bn_name: "ভেড়ামারা",
    url: "bheramara.kushtia.gov.bd",
  },
  {
    id: "202",
    district_id: "26",
    name: "Shalikha Upazila",
    bn_name: "শালিখা",
    url: "shalikha.magura.gov.bd",
  },
  {
    id: "203",
    district_id: "26",
    name: "Sreepur Upazila",
    bn_name: "শ্রীপুর",
    url: "sreepur.magura.gov.bd",
  },
  {
    id: "204",
    district_id: "26",
    name: "Magura Sadar Upazila",
    bn_name: "মাগুরা সদর",
    url: "magurasadar.magura.gov.bd",
  },
  {
    id: "205",
    district_id: "26",
    name: "Mohammadpur Upazila",
    bn_name: "মহম্মদপুর",
    url: "mohammadpur.magura.gov.bd",
  },
  {
    id: "206",
    district_id: "27",
    name: "Paikgasa Upazila",
    bn_name: "পাইকগাছা",
    url: "paikgasa.khulna.gov.bd",
  },
  {
    id: "207",
    district_id: "27",
    name: "Fultola Upazila",
    bn_name: "ফুলতলা",
    url: "fultola.khulna.gov.bd",
  },
  {
    id: "208",
    district_id: "27",
    name: "Digholia Upazila",
    bn_name: "দিঘলিয়া",
    url: "digholia.khulna.gov.bd",
  },
  {
    id: "209",
    district_id: "27",
    name: "Rupsha Upazila",
    bn_name: "রূপসা",
    url: "rupsha.khulna.gov.bd",
  },
  {
    id: "210",
    district_id: "27",
    name: "Terokhada Upazila",
    bn_name: "তেরখাদা",
    url: "terokhada.khulna.gov.bd",
  },
  {
    id: "211",
    district_id: "27",
    name: "Dumuria Upazila",
    bn_name: "ডুমুরিয়া",
    url: "dumuria.khulna.gov.bd",
  },
  {
    id: "212",
    district_id: "27",
    name: "Botiaghata Upazila",
    bn_name: "বটিয়াঘাটা",
    url: "botiaghata.khulna.gov.bd",
  },
  {
    id: "213",
    district_id: "27",
    name: "Dakop Upazila",
    bn_name: "দাকোপ",
    url: "dakop.khulna.gov.bd",
  },
  {
    id: "214",
    district_id: "27",
    name: "Koyra Upazila",
    bn_name: "কয়রা",
    url: "koyra.khulna.gov.bd",
  },
  {
    id: "215",
    district_id: "28",
    name: "Fakirhat Upazila",
    bn_name: "ফকিরহাট",
    url: "fakirhat.bagerhat.gov.bd",
  },
  {
    id: "216",
    district_id: "28",
    name: "Bagerhat Sadar Upazila",
    bn_name: "বাগেরহাট সদর",
    url: "sadar.bagerhat.gov.bd",
  },
  {
    id: "217",
    district_id: "28",
    name: "Mollahat Upazila",
    bn_name: "মোল্লাহাট",
    url: "mollahat.bagerhat.gov.bd",
  },
  {
    id: "218",
    district_id: "28",
    name: "Sarankhola Upazila",
    bn_name: "শরণখোলা",
    url: "sarankhola.bagerhat.gov.bd",
  },
  {
    id: "219",
    district_id: "28",
    name: "Rampal Upazila",
    bn_name: "রামপাল",
    url: "rampal.bagerhat.gov.bd",
  },
  {
    id: "220",
    district_id: "28",
    name: "Morrelganj Upazila",
    bn_name: "মোড়েলগঞ্জ",
    url: "morrelganj.bagerhat.gov.bd",
  },
  {
    id: "221",
    district_id: "28",
    name: "Kachua Upazila",
    bn_name: "কচুয়া",
    url: "kachua.bagerhat.gov.bd",
  },
  {
    id: "222",
    district_id: "28",
    name: "Mongla Upazila",
    bn_name: "মোংলা",
    url: "mongla.bagerhat.gov.bd",
  },
  {
    id: "223",
    district_id: "28",
    name: "Chitalmari Upazila",
    bn_name: "চিতলমারী",
    url: "chitalmari.bagerhat.gov.bd",
  },
  {
    id: "224",
    district_id: "29",
    name: "Jhenaidah Sadar Upazila",
    bn_name: "ঝিনাইদহ সদর",
    url: "sadar.jhenaidah.gov.bd",
  },
  {
    id: "225",
    district_id: "29",
    name: "Shailkupa Upazila",
    bn_name: "শৈলকুপা",
    url: "shailkupa.jhenaidah.gov.bd",
  },
  {
    id: "226",
    district_id: "29",
    name: "Harinakundu Upazila",
    bn_name: "হরিণাকুন্ডু",
    url: "harinakundu.jhenaidah.gov.bd",
  },
  {
    id: "227",
    district_id: "29",
    name: "Kaliganj Upazila",
    bn_name: "কালীগঞ্জ",
    url: "kaliganj.jhenaidah.gov.bd",
  },
  {
    id: "228",
    district_id: "29",
    name: "Kotchandpur Upazila",
    bn_name: "কোটচাঁদপুর",
    url: "kotchandpur.jhenaidah.gov.bd",
  },
  {
    id: "229",
    district_id: "29",
    name: "Moheshpur Upazila",
    bn_name: "মহেশপুর",
    url: "moheshpur.jhenaidah.gov.bd",
  },
  {
    id: "230",
    district_id: "30",
    name: "Jhalakathi Sadar Upazila",
    bn_name: "ঝালকাঠি সদর",
    url: "sadar.jhalakathi.gov.bd",
  },
  {
    id: "231",
    district_id: "30",
    name: "Kathalia Upazila",
    bn_name: "কাঠালিয়া",
    url: "kathalia.jhalakathi.gov.bd",
  },
  {
    id: "232",
    district_id: "30",
    name: "Nalchity Upazila",
    bn_name: "নলছিটি",
    url: "nalchity.jhalakathi.gov.bd",
  },
  {
    id: "233",
    district_id: "30",
    name: "Rajapur Upazila",
    bn_name: "রাজাপুর",
    url: "rajapur.jhalakathi.gov.bd",
  },
  {
    id: "234",
    district_id: "31",
    name: "Bauphal Upazila",
    bn_name: "বাউফল",
    url: "bauphal.patuakhali.gov.bd",
  },
  {
    id: "235",
    district_id: "31",
    name: "Patuakhali Sadar Upazila",
    bn_name: "পটুয়াখালী সদর",
    url: "sadar.patuakhali.gov.bd",
  },
  {
    id: "236",
    district_id: "31",
    name: "Dumki Upazila",
    bn_name: "দুমকি",
    url: "dumki.patuakhali.gov.bd",
  },
  {
    id: "237",
    district_id: "31",
    name: "Dashmina Upazila",
    bn_name: "দশমিনা",
    url: "dashmina.patuakhali.gov.bd",
  },
  {
    id: "238",
    district_id: "31",
    name: "Kalapara Upazila",
    bn_name: "কলাপাড়া",
    url: "kalapara.patuakhali.gov.bd",
  },
  {
    id: "239",
    district_id: "31",
    name: "Mirzaganj Upazila",
    bn_name: "মির্জাগঞ্জ",
    url: "mirzaganj.patuakhali.gov.bd",
  },
  {
    id: "240",
    district_id: "31",
    name: "Galachipa Upazila",
    bn_name: "গলাচিপা",
    url: "galachipa.patuakhali.gov.bd",
  },
  {
    id: "241",
    district_id: "31",
    name: "Rangabali Upazila",
    bn_name: "রাঙ্গাবালী",
    url: "rangabali.patuakhali.gov.bd",
  },
  {
    id: "242",
    district_id: "32",
    name: "Pirojpur Sadar Upazila",
    bn_name: "পিরোজপুর সদর",
    url: "sadar.pirojpur.gov.bd",
  },
  {
    id: "243",
    district_id: "32",
    name: "Nazirpur Upazila",
    bn_name: "নাজিরপুর",
    url: "nazirpur.pirojpur.gov.bd",
  },
  {
    id: "244",
    district_id: "32",
    name: "Kawkhali Upazila",
    bn_name: "কাউখালী",
    url: "kawkhali.pirojpur.gov.bd",
  },
  {
    id: "245",
    district_id: "32",
    name: "Zianagar Upazila",
    bn_name: "জিয়ানগর",
    url: "zianagar.pirojpur.gov.bd",
  },
  {
    id: "246",
    district_id: "32",
    name: "Bhandaria Upazila",
    bn_name: "ভান্ডারিয়া",
    url: "bhandaria.pirojpur.gov.bd",
  },
  {
    id: "247",
    district_id: "32",
    name: "Mathbaria Upazila",
    bn_name: "মঠবাড়ীয়া",
    url: "mathbaria.pirojpur.gov.bd",
  },
  {
    id: "248",
    district_id: "32",
    name: "Nesarabad Upazila",
    bn_name: "নেছারাবাদ",
    url: "nesarabad.pirojpur.gov.bd",
  },
  {
    id: "249",
    district_id: "33",
    name: "Barisal Sadar Upazila",
    bn_name: "বরিশাল সদর",
    url: "barisalsadar.barisal.gov.bd",
  },
  {
    id: "250",
    district_id: "33",
    name: "Bakerganj Upazila",
    bn_name: "বাকেরগঞ্জ",
    url: "bakerganj.barisal.gov.bd",
  },
  {
    id: "251",
    district_id: "33",
    name: "Babuganj Upazila",
    bn_name: "বাবুগঞ্জ",
    url: "babuganj.barisal.gov.bd",
  },
  {
    id: "252",
    district_id: "33",
    name: "Wazirpur Upazila",
    bn_name: "উজিরপুর",
    url: "wazirpur.barisal.gov.bd",
  },
  {
    id: "253",
    district_id: "33",
    name: "Banaripara Upazila",
    bn_name: "বানারীপাড়া",
    url: "banaripara.barisal.gov.bd",
  },
  {
    id: "254",
    district_id: "33",
    name: "Gournadi Upazila",
    bn_name: "গৌরনদী",
    url: "gournadi.barisal.gov.bd",
  },
  {
    id: "255",
    district_id: "33",
    name: "Agailjhara Upazila",
    bn_name: "আগৈলঝাড়া",
    url: "agailjhara.barisal.gov.bd",
  },
  {
    id: "256",
    district_id: "33",
    name: "Mehendiganj Upazila",
    bn_name: "মেহেন্দিগঞ্জ",
    url: "mehendiganj.barisal.gov.bd",
  },
  {
    id: "257",
    district_id: "33",
    name: "Muladi Upazila",
    bn_name: "মুলাদী",
    url: "muladi.barisal.gov.bd",
  },
  {
    id: "258",
    district_id: "33",
    name: "Hizla Upazila",
    bn_name: "হিজলা",
    url: "hizla.barisal.gov.bd",
  },
  {
    id: "259",
    district_id: "34",
    name: "Bhola Sadar Upazila",
    bn_name: "ভোলা সদর",
    url: "sadar.bhola.gov.bd",
  },
  {
    id: "260",
    district_id: "34",
    name: "Borhan Sddin Upazila",
    bn_name: "বোরহান উদ্দিন",
    url: "borhanuddin.bhola.gov.bd",
  },
  {
    id: "261",
    district_id: "34",
    name: "Charfesson Upazila",
    bn_name: "চরফ্যাশন",
    url: "charfesson.bhola.gov.bd",
  },
  {
    id: "262",
    district_id: "34",
    name: "Doulatkhan Upazila",
    bn_name: "দৌলতখান",
    url: "doulatkhan.bhola.gov.bd",
  },
  {
    id: "263",
    district_id: "34",
    name: "Monpura Upazila",
    bn_name: "মনপুরা",
    url: "monpura.bhola.gov.bd",
  },
  {
    id: "264",
    district_id: "34",
    name: "Tazumuddin Upazila",
    bn_name: "তজুমদ্দিন",
    url: "tazumuddin.bhola.gov.bd",
  },
  {
    id: "265",
    district_id: "34",
    name: "Lalmohan Upazila",
    bn_name: "লালমোহন",
    url: "lalmohan.bhola.gov.bd",
  },
  {
    id: "266",
    district_id: "35",
    name: "Amtali Upazila",
    bn_name: "আমতলী",
    url: "amtali.barguna.gov.bd",
  },
  {
    id: "267",
    district_id: "35",
    name: "Barguna Sadar Upazila",
    bn_name: "বরগুনা সদর",
    url: "sadar.barguna.gov.bd",
  },
  {
    id: "268",
    district_id: "35",
    name: "Betagi Upazila",
    bn_name: "বেতাগী",
    url: "betagi.barguna.gov.bd",
  },
  {
    id: "269",
    district_id: "35",
    name: "Bamna Upazila",
    bn_name: "বামনা",
    url: "bamna.barguna.gov.bd",
  },
  {
    id: "270",
    district_id: "35",
    name: "Pathorghata Upazila",
    bn_name: "পাথরঘাটা",
    url: "pathorghata.barguna.gov.bd",
  },
  {
    id: "271",
    district_id: "35",
    name: "Taltali Upazila",
    bn_name: "তালতলি",
    url: "taltali.barguna.gov.bd",
  },
  {
    id: "272",
    district_id: "36",
    name: "Balaganj Upazila",
    bn_name: "বালাগঞ্জ",
    url: "balaganj.sylhet.gov.bd",
  },
  {
    id: "273",
    district_id: "36",
    name: "Beanibazar Upazila",
    bn_name: "বিয়ানীবাজার",
    url: "beanibazar.sylhet.gov.bd",
  },
  {
    id: "274",
    district_id: "36",
    name: "Bishwanath Upazila",
    bn_name: "বিশ্বনাথ",
    url: "bishwanath.sylhet.gov.bd",
  },
  {
    id: "275",
    district_id: "36",
    name: "Companiganj Upazila",
    bn_name: "কোম্পানীগঞ্জ",
    url: "companiganj.sylhet.gov.bd",
  },
  {
    id: "276",
    district_id: "36",
    name: "Fenchuganj Upazila",
    bn_name: "ফেঞ্চুগঞ্জ",
    url: "fenchuganj.sylhet.gov.bd",
  },
  {
    id: "277",
    district_id: "36",
    name: "Golapganj Upazila",
    bn_name: "গোলাপগঞ্জ",
    url: "golapganj.sylhet.gov.bd",
  },
  {
    id: "278",
    district_id: "36",
    name: "Gowainghat Upazila",
    bn_name: "গোয়াইনঘাট",
    url: "gowainghat.sylhet.gov.bd",
  },
  {
    id: "279",
    district_id: "36",
    name: "Jaintiapur Upazila",
    bn_name: "জৈন্তাপুর",
    url: "jaintiapur.sylhet.gov.bd",
  },
  {
    id: "280",
    district_id: "36",
    name: "Kanaighat Upazila",
    bn_name: "কানাইঘাট",
    url: "kanaighat.sylhet.gov.bd",
  },
  {
    id: "281",
    district_id: "36",
    name: "Sylhet Sadar Upazila",
    bn_name: "সিলেট সদর",
    url: "sylhetsadar.sylhet.gov.bd",
  },
  {
    id: "282",
    district_id: "36",
    name: "Zakiganj Upazila",
    bn_name: "জকিগঞ্জ",
    url: "zakiganj.sylhet.gov.bd",
  },
  {
    id: "283",
    district_id: "36",
    name: "Dakshinsurma Upazila",
    bn_name: "দক্ষিণ সুরমা",
    url: "dakshinsurma.sylhet.gov.bd",
  },
  {
    id: "284",
    district_id: "36",
    name: "Osmaninagar Upazila",
    bn_name: "ওসমানী নগর",
    url: "osmaninagar.sylhet.gov.bd",
  },
  {
    id: "285",
    district_id: "37",
    name: "Barlekha Upazila",
    bn_name: "বড়লেখা",
    url: "barlekha.moulvibazar.gov.bd",
  },
  {
    id: "286",
    district_id: "37",
    name: "Kamolganj Upazila",
    bn_name: "কমলগঞ্জ",
    url: "kamolganj.moulvibazar.gov.bd",
  },
  {
    id: "287",
    district_id: "37",
    name: "Kulaura Upazila",
    bn_name: "কুলাউড়া",
    url: "kulaura.moulvibazar.gov.bd",
  },
  {
    id: "288",
    district_id: "37",
    name: "Moulvibazar Sadar Upazila",
    bn_name: "মৌলভীবাজার সদর",
    url: "moulvibazarsadar.moulvibazar.gov.bd",
  },
  {
    id: "289",
    district_id: "37",
    name: "Rajnagar Upazila",
    bn_name: "রাজনগর",
    url: "rajnagar.moulvibazar.gov.bd",
  },
  {
    id: "290",
    district_id: "37",
    name: "Sreemangal Upazila",
    bn_name: "শ্রীমঙ্গল",
    url: "sreemangal.moulvibazar.gov.bd",
  },
  {
    id: "291",
    district_id: "37",
    name: "Juri Upazila",
    bn_name: "জুড়ী",
    url: "juri.moulvibazar.gov.bd",
  },
  {
    id: "292",
    district_id: "38",
    name: "Nabiganj Upazila",
    bn_name: "নবীগঞ্জ",
    url: "nabiganj.habiganj.gov.bd",
  },
  {
    id: "293",
    district_id: "38",
    name: "Bahubal Upazila",
    bn_name: "বাহুবল",
    url: "bahubal.habiganj.gov.bd",
  },
  {
    id: "294",
    district_id: "38",
    name: "Ajmiriganj Upazila",
    bn_name: "আজমিরীগঞ্জ",
    url: "ajmiriganj.habiganj.gov.bd",
  },
  {
    id: "295",
    district_id: "38",
    name: "Baniachong Upazila",
    bn_name: "বানিয়াচং",
    url: "baniachong.habiganj.gov.bd",
  },
  {
    id: "296",
    district_id: "38",
    name: "Lakhai Upazila",
    bn_name: "লাখাই",
    url: "lakhai.habiganj.gov.bd",
  },
  {
    id: "297",
    district_id: "38",
    name: "Chunarughat Upazila",
    bn_name: "চুনারুঘাট",
    url: "chunarughat.habiganj.gov.bd",
  },
  {
    id: "298",
    district_id: "38",
    name: "Habiganj Sadar Upazila",
    bn_name: "হবিগঞ্জ সদর",
    url: "habiganjsadar.habiganj.gov.bd",
  },
  {
    id: "299",
    district_id: "38",
    name: "Madhabpur Upazila",
    bn_name: "মাধবপুর",
    url: "madhabpur.habiganj.gov.bd",
  },
  {
    id: "300",
    district_id: "39",
    name: "Sunamganj Sadar Upazila",
    bn_name: "সুনামগঞ্জ সদর",
    url: "sadar.sunamganj.gov.bd",
  },
  {
    id: "301",
    district_id: "39",
    name: "South Sunamganj Upazila",
    bn_name: "দক্ষিণ সুনামগঞ্জ",
    url: "southsunamganj.sunamganj.gov.bd",
  },
  {
    id: "302",
    district_id: "39",
    name: "Bishwambarpur Upazila",
    bn_name: "বিশ্বম্ভরপুর",
    url: "bishwambarpur.sunamganj.gov.bd",
  },
  {
    id: "303",
    district_id: "39",
    name: "Chhatak Upazila",
    bn_name: "ছাতক",
    url: "chhatak.sunamganj.gov.bd",
  },
  {
    id: "304",
    district_id: "39",
    name: "Jagannathpur Upazila",
    bn_name: "জগন্নাথপুর",
    url: "jagannathpur.sunamganj.gov.bd",
  },
  {
    id: "305",
    district_id: "39",
    name: "Dowarabazar Upazila",
    bn_name: "দোয়ারাবাজার",
    url: "dowarabazar.sunamganj.gov.bd",
  },
  {
    id: "306",
    district_id: "39",
    name: "Tahirpur Upazila",
    bn_name: "তাহিরপুর",
    url: "tahirpur.sunamganj.gov.bd",
  },
  {
    id: "307",
    district_id: "39",
    name: "Dharmapasha Upazila",
    bn_name: "ধর্মপাশা",
    url: "dharmapasha.sunamganj.gov.bd",
  },
  {
    id: "308",
    district_id: "39",
    name: "Jamalganj Upazila",
    bn_name: "জামালগঞ্জ",
    url: "jamalganj.sunamganj.gov.bd",
  },
  {
    id: "309",
    district_id: "39",
    name: "Shalla Upazila",
    bn_name: "শাল্লা",
    url: "shalla.sunamganj.gov.bd",
  },
  {
    id: "310",
    district_id: "39",
    name: "Derai Upazila",
    bn_name: "দিরাই",
    url: "derai.sunamganj.gov.bd",
  },
  {
    id: "311",
    district_id: "40",
    name: "Belabo Upazila",
    bn_name: "বেলাবো",
    url: "belabo.narsingdi.gov.bd",
  },
  {
    id: "312",
    district_id: "40",
    name: "Monohardi Upazila",
    bn_name: "মনোহরদী",
    url: "monohardi.narsingdi.gov.bd",
  },
  {
    id: "313",
    district_id: "40",
    name: "Narsingdi Sadar Upazila",
    bn_name: "নরসিংদী সদর",
    url: "narsingdisadar.narsingdi.gov.bd",
  },
  {
    id: "314",
    district_id: "40",
    name: "Palash Upazila",
    bn_name: "পলাশ",
    url: "palash.narsingdi.gov.bd",
  },
  {
    id: "315",
    district_id: "40",
    name: "Raipura Upazila",
    bn_name: "রায়পুরা",
    url: "raipura.narsingdi.gov.bd",
  },
  {
    id: "316",
    district_id: "40",
    name: "Shibpur Upazila",
    bn_name: "শিবপুর",
    url: "shibpur.narsingdi.gov.bd",
  },
  {
    id: "317",
    district_id: "41",
    name: "Kaliganj Upazila",
    bn_name: "কালীগঞ্জ",
    url: "kaliganj.gazipur.gov.bd",
  },
  {
    id: "318",
    district_id: "41",
    name: "Kaliakair Upazila",
    bn_name: "কালিয়াকৈর",
    url: "kaliakair.gazipur.gov.bd",
  },
  {
    id: "319",
    district_id: "41",
    name: "Kapasia Upazila",
    bn_name: "কাপাসিয়া",
    url: "kapasia.gazipur.gov.bd",
  },
  {
    id: "320",
    district_id: "41",
    name: "Gazipur Sadar Upazila",
    bn_name: "গাজীপুর সদর",
    url: "sadar.gazipur.gov.bd",
  },
  {
    id: "321",
    district_id: "41",
    name: "Sreepur Upazila",
    bn_name: "শ্রীপুর",
    url: "sreepur.gazipur.gov.bd",
  },
  {
    id: "322",
    district_id: "42",
    name: "Shariatpur Sadar Upazila",
    bn_name: "শরিয়তপুর সদর",
    url: "sadar.shariatpur.gov.bd",
  },
  {
    id: "323",
    district_id: "42",
    name: "Naria Upazila",
    bn_name: "নড়িয়া",
    url: "naria.shariatpur.gov.bd",
  },
  {
    id: "324",
    district_id: "42",
    name: "Zajira Upazila",
    bn_name: "জাজিরা",
    url: "zajira.shariatpur.gov.bd",
  },
  {
    id: "325",
    district_id: "42",
    name: "Gosairhat Upazila",
    bn_name: "গোসাইরহাট",
    url: "gosairhat.shariatpur.gov.bd",
  },
  {
    id: "326",
    district_id: "42",
    name: "Bhedarganj Upazila",
    bn_name: "ভেদরগঞ্জ",
    url: "bhedarganj.shariatpur.gov.bd",
  },
  {
    id: "327",
    district_id: "42",
    name: "Damudya Upazila",
    bn_name: "ডামুড্যা",
    url: "damudya.shariatpur.gov.bd",
  },
  {
    id: "328",
    district_id: "43",
    name: "Araihazar Upazila",
    bn_name: "আড়াইহাজার",
    url: "araihazar.narayanganj.gov.bd",
  },
  {
    id: "329",
    district_id: "43",
    name: "Bandar Upazila",
    bn_name: "বন্দর",
    url: "bandar.narayanganj.gov.bd",
  },
  {
    id: "330",
    district_id: "43",
    name: "Narayanganj Sadar Upazila",
    bn_name: "নারায়নগঞ্জ সদর",
    url: "narayanganjsadar.narayanganj.gov.bd",
  },
  {
    id: "331",
    district_id: "43",
    name: "Rupganj Upazila",
    bn_name: "রূপগঞ্জ",
    url: "rupganj.narayanganj.gov.bd",
  },
  {
    id: "332",
    district_id: "43",
    name: "Sonargaon Upazila",
    bn_name: "সোনারগাঁ",
    url: "sonargaon.narayanganj.gov.bd",
  },
  {
    id: "333",
    district_id: "44",
    name: "Basail Upazila",
    bn_name: "বাসাইল",
    url: "basail.tangail.gov.bd",
  },
  {
    id: "334",
    district_id: "44",
    name: "Bhuapur Upazila",
    bn_name: "ভুয়াপুর",
    url: "bhuapur.tangail.gov.bd",
  },
  {
    id: "335",
    district_id: "44",
    name: "Delduar Upazila",
    bn_name: "দেলদুয়ার",
    url: "delduar.tangail.gov.bd",
  },
  {
    id: "336",
    district_id: "44",
    name: "Ghatail Upazila",
    bn_name: "ঘাটাইল",
    url: "ghatail.tangail.gov.bd",
  },
  {
    id: "337",
    district_id: "44",
    name: "Gopalpur Upazila",
    bn_name: "গোপালপুর",
    url: "gopalpur.tangail.gov.bd",
  },
  {
    id: "338",
    district_id: "44",
    name: "Madhupur Upazila",
    bn_name: "মধুপুর",
    url: "madhupur.tangail.gov.bd",
  },
  {
    id: "339",
    district_id: "44",
    name: "Mirzapur Upazila",
    bn_name: "মির্জাপুর",
    url: "mirzapur.tangail.gov.bd",
  },
  {
    id: "340",
    district_id: "44",
    name: "Nagarpur Upazila",
    bn_name: "নাগরপুর",
    url: "nagarpur.tangail.gov.bd",
  },
  {
    id: "341",
    district_id: "44",
    name: "Sakhipur Upazila",
    bn_name: "সখিপুর",
    url: "sakhipur.tangail.gov.bd",
  },
  {
    id: "342",
    district_id: "44",
    name: "Tangail Sadar Upazila",
    bn_name: "টাঙ্গাইল সদর",
    url: "tangailsadar.tangail.gov.bd",
  },
  {
    id: "343",
    district_id: "44",
    name: "Kalihati Upazila",
    bn_name: "কালিহাতী",
    url: "kalihati.tangail.gov.bd",
  },
  {
    id: "344",
    district_id: "44",
    name: "Dhanbari Upazila",
    bn_name: "ধনবাড়ী",
    url: "dhanbari.tangail.gov.bd",
  },
  {
    id: "345",
    district_id: "45",
    name: "Itna Upazila",
    bn_name: "ইটনা",
    url: "itna.kishoreganj.gov.bd",
  },
  {
    id: "346",
    district_id: "45",
    name: "Katiadi Upazila",
    bn_name: "কটিয়াদী",
    url: "katiadi.kishoreganj.gov.bd",
  },
  {
    id: "347",
    district_id: "45",
    name: "Bhairab Upazila",
    bn_name: "ভৈরব",
    url: "bhairab.kishoreganj.gov.bd",
  },
  {
    id: "348",
    district_id: "45",
    name: "Tarail Upazila",
    bn_name: "তাড়াইল",
    url: "tarail.kishoreganj.gov.bd",
  },
  {
    id: "349",
    district_id: "45",
    name: "Hossainpur Upazila",
    bn_name: "হোসেনপুর",
    url: "hossainpur.kishoreganj.gov.bd",
  },
  {
    id: "350",
    district_id: "45",
    name: "Pakundia Upazila",
    bn_name: "পাকুন্দিয়া",
    url: "pakundia.kishoreganj.gov.bd",
  },
  {
    id: "351",
    district_id: "45",
    name: "Kuliarchar Upazila",
    bn_name: "কুলিয়ারচর",
    url: "kuliarchar.kishoreganj.gov.bd",
  },
  {
    id: "352",
    district_id: "45",
    name: "Kishoreganj Sadar Upazila",
    bn_name: "কিশোরগঞ্জ সদর",
    url: "kishoreganjsadar.kishoreganj.gov.bd",
  },
  {
    id: "353",
    district_id: "45",
    name: "Karimgonj Upazila",
    bn_name: "করিমগঞ্জ",
    url: "karimgonj.kishoreganj.gov.bd",
  },
  {
    id: "354",
    district_id: "45",
    name: "Bajitpur Upazila",
    bn_name: "বাজিতপুর",
    url: "bajitpur.kishoreganj.gov.bd",
  },
  {
    id: "355",
    district_id: "45",
    name: "Austagram Upazila",
    bn_name: "অষ্টগ্রাম",
    url: "austagram.kishoreganj.gov.bd",
  },
  {
    id: "356",
    district_id: "45",
    name: "Mithamoin Upazila",
    bn_name: "মিঠামইন",
    url: "mithamoin.kishoreganj.gov.bd",
  },
  {
    id: "357",
    district_id: "45",
    name: "Nikli Upazila",
    bn_name: "নিকলী",
    url: "nikli.kishoreganj.gov.bd",
  },
  {
    id: "358",
    district_id: "46",
    name: "Harirampur Upazila",
    bn_name: "হরিরামপুর",
    url: "harirampur.manikganj.gov.bd",
  },
  {
    id: "359",
    district_id: "46",
    name: "Saturia Upazila",
    bn_name: "সাটুরিয়া",
    url: "saturia.manikganj.gov.bd",
  },
  {
    id: "360",
    district_id: "46",
    name: "Manikganj Sadar Upazila",
    bn_name: "মানিকগঞ্জ সদর",
    url: "sadar.manikganj.gov.bd",
  },
  {
    id: "361",
    district_id: "46",
    name: "Gior Upazila",
    bn_name: "ঘিওর",
    url: "gior.manikganj.gov.bd",
  },
  {
    id: "362",
    district_id: "46",
    name: "Shibaloy Upazila",
    bn_name: "শিবালয়",
    url: "shibaloy.manikganj.gov.bd",
  },
  {
    id: "363",
    district_id: "46",
    name: "Doulatpur Upazila",
    bn_name: "দৌলতপুর",
    url: "doulatpur.manikganj.gov.bd",
  },
  {
    id: "364",
    district_id: "46",
    name: "Singiar Upazila",
    bn_name: "সিংগাইর",
    url: "singiar.manikganj.gov.bd",
  },
  {
    id: "365",
    district_id: "47",
    name: "Savar Upazila",
    bn_name: "সাভার",
    url: "savar.dhaka.gov.bd",
  },
  {
    id: "366",
    district_id: "47",
    name: "Dhamrai Upazila",
    bn_name: "ধামরাই",
    url: "dhamrai.dhaka.gov.bd",
  },
  {
    id: "367",
    district_id: "47",
    name: "Keraniganj Upazila",
    bn_name: "কেরাণীগঞ্জ",
    url: "keraniganj.dhaka.gov.bd",
  },
  {
    id: "368",
    district_id: "47",
    name: "Nawabganj Upazila",
    bn_name: "নবাবগঞ্জ",
    url: "nawabganj.dhaka.gov.bd",
  },
  {
    id: "369",
    district_id: "47",
    name: "Dohar Upazila",
    bn_name: "দোহার",
    url: "dohar.dhaka.gov.bd",
  },
  {
    id: "370",
    district_id: "48",
    name: "Munshiganj Sadar Upazila",
    bn_name: "মুন্সিগঞ্জ সদর",
    url: "sadar.munshiganj.gov.bd",
  },
  {
    id: "371",
    district_id: "48",
    name: "Sreenagar Upazila",
    bn_name: "শ্রীনগর",
    url: "sreenagar.munshiganj.gov.bd",
  },
  {
    id: "372",
    district_id: "48",
    name: "Sirajdikhan Upazila",
    bn_name: "সিরাজদিখান",
    url: "sirajdikhan.munshiganj.gov.bd",
  },
  {
    id: "373",
    district_id: "48",
    name: "Louhajanj Upazila",
    bn_name: "লৌহজং",
    url: "louhajanj.munshiganj.gov.bd",
  },
  {
    id: "374",
    district_id: "48",
    name: "Gajaria Upazila",
    bn_name: "গজারিয়া",
    url: "gajaria.munshiganj.gov.bd",
  },
  {
    id: "375",
    district_id: "48",
    name: "Tongibari Upazila",
    bn_name: "টংগীবাড়ি",
    url: "tongibari.munshiganj.gov.bd",
  },
  {
    id: "376",
    district_id: "49",
    name: "Rajbari Sadar Upazila",
    bn_name: "রাজবাড়ী সদর",
    url: "sadar.rajbari.gov.bd",
  },
  {
    id: "377",
    district_id: "49",
    name: "Goalanda Upazila",
    bn_name: "গোয়ালন্দ",
    url: "goalanda.rajbari.gov.bd",
  },
  {
    id: "378",
    district_id: "49",
    name: "Pangsa Upazila",
    bn_name: "পাংশা",
    url: "pangsa.rajbari.gov.bd",
  },
  {
    id: "379",
    district_id: "49",
    name: "Baliakandi Upazila",
    bn_name: "বালিয়াকান্দি",
    url: "baliakandi.rajbari.gov.bd",
  },
  {
    id: "380",
    district_id: "49",
    name: "Kalukhali Upazila",
    bn_name: "কালুখালী",
    url: "kalukhali.rajbari.gov.bd",
  },
  {
    id: "381",
    district_id: "50",
    name: "Madaripur Sadar Upazila",
    bn_name: "মাদারীপুর সদর",
    url: "sadar.madaripur.gov.bd",
  },
  {
    id: "382",
    district_id: "50",
    name: "Shibchar Upazila",
    bn_name: "শিবচর",
    url: "shibchar.madaripur.gov.bd",
  },
  {
    id: "383",
    district_id: "50",
    name: "Kalkini Upazila",
    bn_name: "কালকিনি",
    url: "kalkini.madaripur.gov.bd",
  },
  {
    id: "384",
    district_id: "50",
    name: "Rajoir Upazila",
    bn_name: "রাজৈর",
    url: "rajoir.madaripur.gov.bd",
  },
  {
    id: "385",
    district_id: "51",
    name: "Gopalganj Sadar Upazila",
    bn_name: "গোপালগঞ্জ সদর",
    url: "sadar.gopalganj.gov.bd",
  },
  {
    id: "386",
    district_id: "51",
    name: "Kashiani Upazila",
    bn_name: "কাশিয়ানী",
    url: "kashiani.gopalganj.gov.bd",
  },
  {
    id: "387",
    district_id: "51",
    name: "Tungipara Upazila",
    bn_name: "টুংগীপাড়া",
    url: "tungipara.gopalganj.gov.bd",
  },
  {
    id: "388",
    district_id: "51",
    name: "Kotalipara Upazila",
    bn_name: "কোটালীপাড়া",
    url: "kotalipara.gopalganj.gov.bd",
  },
  {
    id: "389",
    district_id: "51",
    name: "Muksudpur Upazila",
    bn_name: "মুকসুদপুর",
    url: "muksudpur.gopalganj.gov.bd",
  },
  {
    id: "390",
    district_id: "52",
    name: "Faridpur Sadar Upazila",
    bn_name: "ফরিদপুর সদর",
    url: "sadar.faridpur.gov.bd",
  },
  {
    id: "391",
    district_id: "52",
    name: "Alfadanga Upazila",
    bn_name: "আলফাডাঙ্গা",
    url: "alfadanga.faridpur.gov.bd",
  },
  {
    id: "392",
    district_id: "52",
    name: "Boalmari Upazila",
    bn_name: "বোয়ালমারী",
    url: "boalmari.faridpur.gov.bd",
  },
  {
    id: "393",
    district_id: "52",
    name: "Sadarpur Upazila",
    bn_name: "সদরপুর",
    url: "sadarpur.faridpur.gov.bd",
  },
  {
    id: "394",
    district_id: "52",
    name: "Nagarkanda Upazila",
    bn_name: "নগরকান্দা",
    url: "nagarkanda.faridpur.gov.bd",
  },
  {
    id: "395",
    district_id: "52",
    name: "Bhanga Upazila",
    bn_name: "ভাঙ্গা",
    url: "bhanga.faridpur.gov.bd",
  },
  {
    id: "396",
    district_id: "52",
    name: "Charbhadrasan Upazila",
    bn_name: "চরভদ্রাসন",
    url: "charbhadrasan.faridpur.gov.bd",
  },
  {
    id: "397",
    district_id: "52",
    name: "Madhukhali Upazila",
    bn_name: "মধুখালী",
    url: "madhukhali.faridpur.gov.bd",
  },
  {
    id: "398",
    district_id: "52",
    name: "Saltha Upazila",
    bn_name: "সালথা",
    url: "saltha.faridpur.gov.bd",
  },
  {
    id: "399",
    district_id: "53",
    name: "Panchagarh Sadar Upazila",
    bn_name: "পঞ্চগড় সদর",
    url: "panchagarhsadar.panchagarh.gov.bd",
  },
  {
    id: "400",
    district_id: "53",
    name: "Debiganj Upazila",
    bn_name: "দেবীগঞ্জ",
    url: "debiganj.panchagarh.gov.bd",
  },
  {
    id: "401",
    district_id: "53",
    name: "Boda Upazila",
    bn_name: "বোদা",
    url: "boda.panchagarh.gov.bd",
  },
  {
    id: "402",
    district_id: "53",
    name: "Atwari Upazila",
    bn_name: "আটোয়ারী",
    url: "atwari.panchagarh.gov.bd",
  },
  {
    id: "403",
    district_id: "53",
    name: "Tetulia Upazila",
    bn_name: "তেতুলিয়া",
    url: "tetulia.panchagarh.gov.bd",
  },
  {
    id: "404",
    district_id: "54",
    name: "Nawabganj Upazila",
    bn_name: "নবাবগঞ্জ",
    url: "nawabganj.dinajpur.gov.bd",
  },
  {
    id: "405",
    district_id: "54",
    name: "Birganj Upazila",
    bn_name: "বীরগঞ্জ",
    url: "birganj.dinajpur.gov.bd",
  },
  {
    id: "406",
    district_id: "54",
    name: "Ghoraghat Upazila",
    bn_name: "ঘোড়াঘাট",
    url: "ghoraghat.dinajpur.gov.bd",
  },
  {
    id: "407",
    district_id: "54",
    name: "Birampur Upazila",
    bn_name: "বিরামপুর",
    url: "birampur.dinajpur.gov.bd",
  },
  {
    id: "408",
    district_id: "54",
    name: "Parbatipur Upazila",
    bn_name: "পার্বতীপুর",
    url: "parbatipur.dinajpur.gov.bd",
  },
  {
    id: "409",
    district_id: "54",
    name: "Bochaganj Upazila",
    bn_name: "বোচাগঞ্জ",
    url: "bochaganj.dinajpur.gov.bd",
  },
  {
    id: "410",
    district_id: "54",
    name: "Kaharol Upazila",
    bn_name: "কাহারোল",
    url: "kaharol.dinajpur.gov.bd",
  },
  {
    id: "411",
    district_id: "54",
    name: "Fulbari Upazila",
    bn_name: "ফুলবাড়ী",
    url: "fulbari.dinajpur.gov.bd",
  },
  {
    id: "412",
    district_id: "54",
    name: "Dinajpur Sadar Upazila",
    bn_name: "দিনাজপুর সদর",
    url: "dinajpursadar.dinajpur.gov.bd",
  },
  {
    id: "413",
    district_id: "54",
    name: "Hakimpur Upazila",
    bn_name: "হাকিমপুর",
    url: "hakimpur.dinajpur.gov.bd",
  },
  {
    id: "414",
    district_id: "54",
    name: "Khansama Upazila",
    bn_name: "খানসামা",
    url: "khansama.dinajpur.gov.bd",
  },
  {
    id: "415",
    district_id: "54",
    name: "Birol Upazila",
    bn_name: "বিরল",
    url: "birol.dinajpur.gov.bd",
  },
  {
    id: "416",
    district_id: "54",
    name: "Chirirbandar Upazila",
    bn_name: "চিরিরবন্দর",
    url: "chirirbandar.dinajpur.gov.bd",
  },
  {
    id: "417",
    district_id: "55",
    name: "Lalmonirhat Sadar Upazila",
    bn_name: "লালমনিরহাট সদর",
    url: "sadar.lalmonirhat.gov.bd",
  },
  {
    id: "418",
    district_id: "55",
    name: "Kaliganj Upazila",
    bn_name: "কালীগঞ্জ",
    url: "kaliganj.lalmonirhat.gov.bd",
  },
  {
    id: "419",
    district_id: "55",
    name: "Hatibandha Upazila",
    bn_name: "হাতীবান্ধা",
    url: "hatibandha.lalmonirhat.gov.bd",
  },
  {
    id: "420",
    district_id: "55",
    name: "Patgram Upazila",
    bn_name: "পাটগ্রাম",
    url: "patgram.lalmonirhat.gov.bd",
  },
  {
    id: "421",
    district_id: "55",
    name: "Aditmari Upazila",
    bn_name: "আদিতমারী",
    url: "aditmari.lalmonirhat.gov.bd",
  },
  {
    id: "422",
    district_id: "56",
    name: "Syedpur Upazila",
    bn_name: "সৈয়দপুর",
    url: "syedpur.nilphamari.gov.bd",
  },
  {
    id: "423",
    district_id: "56",
    name: "Domar Upazila",
    bn_name: "ডোমার",
    url: "domar.nilphamari.gov.bd",
  },
  {
    id: "424",
    district_id: "56",
    name: "Dimla Upazila",
    bn_name: "ডিমলা",
    url: "dimla.nilphamari.gov.bd",
  },
  {
    id: "425",
    district_id: "56",
    name: "Jaldhaka Upazila",
    bn_name: "জলঢাকা",
    url: "jaldhaka.nilphamari.gov.bd",
  },
  {
    id: "426",
    district_id: "56",
    name: "Kishorganj Upazila",
    bn_name: "কিশোরগঞ্জ",
    url: "kishorganj.nilphamari.gov.bd",
  },
  {
    id: "427",
    district_id: "56",
    name: "Nilphamari Sadar Upazila",
    bn_name: "নীলফামারী সদর",
    url: "nilphamarisadar.nilphamari.gov.bd",
  },
  {
    id: "428",
    district_id: "57",
    name: "Sadullapur Upazila",
    bn_name: "সাদুল্লাপুর",
    url: "sadullapur.gaibandha.gov.bd",
  },
  {
    id: "429",
    district_id: "57",
    name: "Gaibandha Sadar Upazila",
    bn_name: "গাইবান্ধা সদর",
    url: "gaibandhasadar.gaibandha.gov.bd",
  },
  {
    id: "430",
    district_id: "57",
    name: "Palashbari Upazila",
    bn_name: "পলাশবাড়ী",
    url: "palashbari.gaibandha.gov.bd",
  },
  {
    id: "431",
    district_id: "57",
    name: "Saghata Upazila",
    bn_name: "সাঘাটা",
    url: "saghata.gaibandha.gov.bd",
  },
  {
    id: "432",
    district_id: "57",
    name: "Gobindaganj Upazila",
    bn_name: "গোবিন্দগঞ্জ",
    url: "gobindaganj.gaibandha.gov.bd",
  },
  {
    id: "433",
    district_id: "57",
    name: "Sundarganj Upazila",
    bn_name: "সুন্দরগঞ্জ",
    url: "sundarganj.gaibandha.gov.bd",
  },
  {
    id: "434",
    district_id: "57",
    name: "Phulchari Upazila",
    bn_name: "ফুলছড়ি",
    url: "phulchari.gaibandha.gov.bd",
  },
  {
    id: "435",
    district_id: "58",
    name: "Thakurgaon Sadar Upazila",
    bn_name: "ঠাকুরগাঁও সদর",
    url: "thakurgaonsadar.thakurgaon.gov.bd",
  },
  {
    id: "436",
    district_id: "58",
    name: "Pirganj Upazila",
    bn_name: "পীরগঞ্জ",
    url: "pirganj.thakurgaon.gov.bd",
  },
  {
    id: "437",
    district_id: "58",
    name: "Ranisankail Upazila",
    bn_name: "রাণীশংকৈল",
    url: "ranisankail.thakurgaon.gov.bd",
  },
  {
    id: "438",
    district_id: "58",
    name: "Haripur Upazila",
    bn_name: "হরিপুর",
    url: "haripur.thakurgaon.gov.bd",
  },
  {
    id: "439",
    district_id: "58",
    name: "Baliadangi Upazila",
    bn_name: "বালিয়াডাঙ্গী",
    url: "baliadangi.thakurgaon.gov.bd",
  },
  {
    id: "440",
    district_id: "59",
    name: "Rangpur Sadar Upazila",
    bn_name: "রংপুর সদর",
    url: "rangpursadar.rangpur.gov.bd",
  },
  {
    id: "441",
    district_id: "59",
    name: "Gangachara Upazila",
    bn_name: "গংগাচড়া",
    url: "gangachara.rangpur.gov.bd",
  },
  {
    id: "442",
    district_id: "59",
    name: "Taragonj Upazila",
    bn_name: "তারাগঞ্জ",
    url: "taragonj.rangpur.gov.bd",
  },
  {
    id: "443",
    district_id: "59",
    name: "Badargonj Upazila",
    bn_name: "বদরগঞ্জ",
    url: "badargonj.rangpur.gov.bd",
  },
  {
    id: "444",
    district_id: "59",
    name: "Mithapukur Upazila",
    bn_name: "মিঠাপুকুর",
    url: "mithapukur.rangpur.gov.bd",
  },
  {
    id: "445",
    district_id: "59",
    name: "Pirgonj Upazila",
    bn_name: "পীরগঞ্জ",
    url: "pirgonj.rangpur.gov.bd",
  },
  {
    id: "446",
    district_id: "59",
    name: "Kaunia Upazila",
    bn_name: "কাউনিয়া",
    url: "kaunia.rangpur.gov.bd",
  },
  {
    id: "447",
    district_id: "59",
    name: "Pirgacha Upazila",
    bn_name: "পীরগাছা",
    url: "pirgacha.rangpur.gov.bd",
  },
  {
    id: "448",
    district_id: "60",
    name: "Kurigram Sadar Upazila",
    bn_name: "কুড়িগ্রাম সদর",
    url: "kurigramsadar.kurigram.gov.bd",
  },
  {
    id: "449",
    district_id: "60",
    name: "Nageshwari Upazila",
    bn_name: "নাগেশ্বরী",
    url: "nageshwari.kurigram.gov.bd",
  },
  {
    id: "450",
    district_id: "60",
    name: "Bhurungamari Upazila",
    bn_name: "ভুরুঙ্গামারী",
    url: "bhurungamari.kurigram.gov.bd",
  },
  {
    id: "451",
    district_id: "60",
    name: "Phulbari Upazila",
    bn_name: "ফুলবাড়ী",
    url: "phulbari.kurigram.gov.bd",
  },
  {
    id: "452",
    district_id: "60",
    name: "Rajarhat Upazila",
    bn_name: "রাজারহাট",
    url: "rajarhat.kurigram.gov.bd",
  },
  {
    id: "453",
    district_id: "60",
    name: "Ulipur Upazila",
    bn_name: "উলিপুর",
    url: "ulipur.kurigram.gov.bd",
  },
  {
    id: "454",
    district_id: "60",
    name: "Chilmari Upazila",
    bn_name: "চিলমারী",
    url: "chilmari.kurigram.gov.bd",
  },
  {
    id: "455",
    district_id: "60",
    name: "Rowmari Upazila",
    bn_name: "রৌমারী",
    url: "rowmari.kurigram.gov.bd",
  },
  {
    id: "456",
    district_id: "60",
    name: "Charrajibpur Upazila",
    bn_name: "চর রাজিবপুর",
    url: "charrajibpur.kurigram.gov.bd",
  },
  {
    id: "457",
    district_id: "61",
    name: "Sherpur Sadar Upazila",
    bn_name: "শেরপুর সদর",
    url: "sherpursadar.sherpur.gov.bd",
  },
  {
    id: "458",
    district_id: "61",
    name: "Nalitabari Upazila",
    bn_name: "নালিতাবাড়ী",
    url: "nalitabari.sherpur.gov.bd",
  },
  {
    id: "459",
    district_id: "61",
    name: "Sreebordi Upazila",
    bn_name: "শ্রীবরদী",
    url: "sreebordi.sherpur.gov.bd",
  },
  {
    id: "460",
    district_id: "61",
    name: "Nokla Upazila",
    bn_name: "নকলা",
    url: "nokla.sherpur.gov.bd",
  },
  {
    id: "461",
    district_id: "61",
    name: "Jhenaigati Upazila",
    bn_name: "ঝিনাইগাতী",
    url: "jhenaigati.sherpur.gov.bd",
  },
  {
    id: "462",
    district_id: "62",
    name: "Fulbaria Upazila",
    bn_name: "ফুলবাড়ীয়া",
    url: "fulbaria.mymensingh.gov.bd",
  },
  {
    id: "463",
    district_id: "62",
    name: "Trishal Upazila",
    bn_name: "ত্রিশাল",
    url: "trishal.mymensingh.gov.bd",
  },
  {
    id: "464",
    district_id: "62",
    name: "Bhaluka Upazila",
    bn_name: "ভালুকা",
    url: "bhaluka.mymensingh.gov.bd",
  },
  {
    id: "465",
    district_id: "62",
    name: "Muktagacha Upazila",
    bn_name: "মুক্তাগাছা",
    url: "muktagacha.mymensingh.gov.bd",
  },
  {
    id: "466",
    district_id: "62",
    name: "Mymensingh Sadar Upazila",
    bn_name: "ময়মনসিংহ সদর",
    url: "mymensinghsadar.mymensingh.gov.bd",
  },
  {
    id: "467",
    district_id: "62",
    name: "Dhobaura Upazila",
    bn_name: "ধোবাউড়া",
    url: "dhobaura.mymensingh.gov.bd",
  },
  {
    id: "468",
    district_id: "62",
    name: "Phulpur Upazila",
    bn_name: "ফুলপুর",
    url: "phulpur.mymensingh.gov.bd",
  },
  {
    id: "469",
    district_id: "62",
    name: "Haluaghat Upazila",
    bn_name: "হালুয়াঘাট",
    url: "haluaghat.mymensingh.gov.bd",
  },
  {
    id: "470",
    district_id: "62",
    name: "Gouripur Upazila",
    bn_name: "গৌরীপুর",
    url: "gouripur.mymensingh.gov.bd",
  },
  {
    id: "471",
    district_id: "62",
    name: "Gafargaon Upazila",
    bn_name: "গফরগাঁও",
    url: "gafargaon.mymensingh.gov.bd",
  },
  {
    id: "472",
    district_id: "62",
    name: "Iswarganj Upazila",
    bn_name: "ঈশ্বরগঞ্জ",
    url: "iswarganj.mymensingh.gov.bd",
  },
  {
    id: "473",
    district_id: "62",
    name: "Nandail Upazila",
    bn_name: "নান্দাইল",
    url: "nandail.mymensingh.gov.bd",
  },
  {
    id: "474",
    district_id: "62",
    name: "Tarakanda Upazila",
    bn_name: "তারাকান্দা",
    url: "tarakanda.mymensingh.gov.bd",
  },
  {
    id: "475",
    district_id: "63",
    name: "Jamalpur Sadar Upazila",
    bn_name: "জামালপুর সদর",
    url: "jamalpursadar.jamalpur.gov.bd",
  },
  {
    id: "476",
    district_id: "63",
    name: "Melandah Upazila",
    bn_name: "মেলান্দহ",
    url: "melandah.jamalpur.gov.bd",
  },
  {
    id: "477",
    district_id: "63",
    name: "Islampur Upazila",
    bn_name: "ইসলামপুর",
    url: "islampur.jamalpur.gov.bd",
  },
  {
    id: "478",
    district_id: "63",
    name: "Dewangonj Upazila",
    bn_name: "দেওয়ানগঞ্জ",
    url: "dewangonj.jamalpur.gov.bd",
  },
  {
    id: "479",
    district_id: "63",
    name: "Sarishabari Upazila",
    bn_name: "সরিষাবাড়ী",
    url: "sarishabari.jamalpur.gov.bd",
  },
  {
    id: "480",
    district_id: "63",
    name: "Madarganj Upazila",
    bn_name: "মাদারগঞ্জ",
    url: "madarganj.jamalpur.gov.bd",
  },
  {
    id: "481",
    district_id: "63",
    name: "Bokshiganj Upazila",
    bn_name: "বকশীগঞ্জ",
    url: "bokshiganj.jamalpur.gov.bd",
  },
  {
    id: "482",
    district_id: "64",
    name: "Barhatta Upazila",
    bn_name: "বারহাট্টা",
    url: "barhatta.netrokona.gov.bd",
  },
  {
    id: "483",
    district_id: "64",
    name: "Durgapur Upazila",
    bn_name: "দুর্গাপুর",
    url: "durgapur.netrokona.gov.bd",
  },
  {
    id: "484",
    district_id: "64",
    name: "Kendua Upazila",
    bn_name: "কেন্দুয়া",
    url: "kendua.netrokona.gov.bd",
  },
  {
    id: "485",
    district_id: "64",
    name: "Atpara Upazila",
    bn_name: "আটপাড়া",
    url: "atpara.netrokona.gov.bd",
  },
  {
    id: "486",
    district_id: "64",
    name: "Madan Upazila",
    bn_name: "মদন",
    url: "madan.netrokona.gov.bd",
  },
  {
    id: "487",
    district_id: "64",
    name: "Khaliajuri Upazila",
    bn_name: "খালিয়াজুরী",
    url: "khaliajuri.netrokona.gov.bd",
  },
  {
    id: "488",
    district_id: "64",
    name: "Kalmakanda Upazila",
    bn_name: "কলমাকান্দা",
    url: "kalmakanda.netrokona.gov.bd",
  },
  {
    id: "489",
    district_id: "64",
    name: "Mohongonj Upazila",
    bn_name: "মোহনগঞ্জ",
    url: "mohongonj.netrokona.gov.bd",
  },
  {
    id: "490",
    district_id: "64",
    name: "Purbadhala Upazila",
    bn_name: "পূর্বধলা",
    url: "purbadhala.netrokona.gov.bd",
  },
  {
    id: "491",
    district_id: "64",
    name: "Netrokona Sadar Upazila",
    bn_name: "নেত্রকোণা সদর",
    url: "netrokonasadar.netrokona.gov.bd",
  },
  {
    id: "492",
    district_id: "9",
    name: "Eidgaon Upazila",
    bn_name: "ঈদগাঁও",
    url: "null",
  },
  {
    id: "493",
    district_id: "39",
    name: "Madhyanagar Upazila",
    bn_name: "মধ্যনগর",
    url: "null",
  },
  {
    id: "494",
    district_id: "50",
    name: "Dasar Upazila",
    bn_name: "ডাসার",
    url: "null",
  },
];
const district = [
  {
    name: "Barguna District",
    districtbn: "বরগুনা",
    coordinates: [22.0953, 90.1121],
  },
  {
    name: "Barishal District",
    districtbn: "বরিশাল",
    coordinates: [22.7022, 90.3696],
  },
  {
    name: "Bhola District",
    districtbn: "ভোলা",
    coordinates: [22.1785, 90.7101],
  },
  {
    name: "Jhalokati District",
    districtbn: "ঝালকাঠী",
    coordinates: [22.5721, 90.187],
  },
  {
    name: "Patuakhali District",
    districtbn: "পটুয়াখালী",
    coordinates: [22.2249, 90.4548],
  },
  {
    name: "Pirojpur District",
    districtbn: "পিরোজপুর",
    coordinates: [22.5791, 89.9759],
  },
  {
    name: "Bandarban District",
    districtbn: "বান্দরবান",
    coordinates: [21.8311, 92.3686],
  },
  {
    name: "Brahmanbaria District",
    districtbn: "ব্রাহ্মণবাড়িয়া",
    coordinates: [23.9608, 91.1115],
  },
  {
    name: "Chandpur District",
    districtbn: "চাঁদপুর",
    coordinates: [23.2513, 90.8518],
  },
  {
    name: "Chattogram District",
    districtbn: "চট্টগ্রাম",
    coordinates: [22.515, 91.7539],
  },
  {
    name: "Cox District's Bazar",
    districtbn: "কক্স বাজার",
    coordinates: [21.5641, 92.0282],
  },
  {
    name: "Cumilla District",
    districtbn: "কুমিল্লা",
    coordinates: [23.4576, 91.1809],
  },
  {
    name: "Feni District",
    districtbn: "ফেনী",
    coordinates: [22.9409, 91.4067],
  },
  {
    name: "Khagrachari District",
    districtbn: "খাগড়াছড়ি",
    coordinates: [23.1322, 91.949],
  },
  {
    name: "Lakshmipur District",
    districtbn: "লক্ষ্মীপুর",
    coordinates: [22.9447, 90.8282],
  },
  {
    name: "Noakhali District",
    districtbn: "নোয়াখালী",
    coordinates: [22.8724, 91.0973],
  },
  {
    name: "Rangamati District",
    districtbn: "রাঙ্গামাটি",
    coordinates: [22.7324, 92.2985],
  },
  {
    name: "Dhaka District",
    districtbn: "ঢাকা",
    coordinates: [23.8105, 90.3372],
  },
  {
    name: "Faridpur District",
    districtbn: "ফরিদপুর",
    coordinates: [23.5424, 89.6309],
  },
  {
    name: "Gazipur District",
    districtbn: "গাজীপুর",
    coordinates: [24.0958, 90.4125],
  },
  {
    name: "Gopalganj District",
    districtbn: "গোপালগঞ্জ",
    coordinates: [23.0488, 89.8879],
  },
  {
    name: "Kishoreganj District",
    districtbn: "কিশোরগঞ্জ",
    coordinates: [24.426, 90.9821],
  },
  {
    name: "Madaripur District",
    districtbn: "মাদারীপুর",
    coordinates: [23.2393, 90.187],
  },
  {
    name: "Manikganj District",
    districtbn: "মানিকগঞ্জ",
    coordinates: [23.8617, 90.0003],
  },
  {
    name: "Munshiganj District",
    districtbn: "মুন্সিগঞ্জ",
    coordinates: [23.4981, 90.4127],
  },
  {
    name: "Narayanganj District",
    districtbn: "নারায়ণগঞ্জ",
    coordinates: [23.7147, 90.5636],
  },
  {
    name: "Narsingdi District",
    districtbn: "নরসিংদী",
    coordinates: [24.1344, 90.786],
  },
  {
    name: "Rajbari District",
    districtbn: "রাজবাড়ী",
    coordinates: [23.7151, 89.5875],
  },
  {
    name: "Shariatpur District",
    districtbn: "শরিয়তপুর",
    coordinates: [23.2423, 90.4348],
  },
  {
    name: "Tangail District",
    districtbn: "টাঙ্গাইল",
    coordinates: [24.3917, 89.9948],
  },
  {
    name: "Bagerhat District",
    districtbn: "বাগেরহাট",
    coordinates: [22.6602, 89.7895],
  },
  {
    name: "Chuadanga District",
    districtbn: "চুয়াডাঙ্গা",
    coordinates: [23.6161, 88.8263],
  },
  {
    name: "Jashore District",
    districtbn: "যশোর",
    coordinates: [23.1634, 89.2182],
  },
  {
    name: "Jhenaidah District",
    districtbn: "ঝিনাইদহ",
    coordinates: [23.545, 89.1726],
  },
  {
    name: "Khulna District",
    districtbn: "খুলনা",
    coordinates: [22.6738, 89.3967],
  },
  {
    name: "Kushtia District",
    districtbn: "কুষ্টিয়া",
    coordinates: [23.8907, 89.1099],
  },
  {
    name: "Magura District",
    districtbn: "মাগুরা",
    coordinates: [23.429, 89.4364],
  },
  {
    name: "Meherpur District",
    districtbn: "মেহেরপুর",
    coordinates: [23.8052, 88.6724],
  },
  {
    name: "Narail District",
    districtbn: "নড়াইল",
    coordinates: [23.1163, 89.584],
  },
  {
    name: "Satkhira District",
    districtbn: "সাতক্ষীরা",
    coordinates: [22.3155, 89.1115],
  },
  {
    name: "Jamalpur District",
    districtbn: "জামালপুর",
    coordinates: [25.0831, 89.7853],
  },
  {
    name: "Mymensingh District",
    districtbn: "ময়মনসিংহ",
    coordinates: [24.7539, 90.4073],
  },
  {
    name: "Netrokona District",
    districtbn: "নেত্রকোনা",
    coordinates: [24.8103, 90.8656],
  },
  {
    name: "Sherpur District",
    districtbn: "শেরপুর",
    coordinates: [25.0746, 90.1495],
  },
  {
    name: "Bogura District",
    districtbn: "বগুড়া",
    coordinates: [24.851, 89.3697],
  },
  {
    name: "Joypurhat District",
    districtbn: "জয়পুরহাট",
    coordinates: [25.0947, 89.0945],
  },
  {
    name: "Naogaon District",
    districtbn: "নওগাঁ",
    coordinates: [24.9132, 88.7531],
  },
  {
    name: "Natore District",
    districtbn: "নাটোর",
    coordinates: [24.4102, 89.0076],
  },
  {
    name: "Chapai District Nawabganj",
    districtbn: "চাঁপাইনবাবগঞ্জ",
    coordinates: [24.7413, 88.2912],
  },
  {
    name: "Pabna District",
    districtbn: "পাবনা",
    coordinates: [24.1585, 89.4481],
  },
  {
    name: "Rajshahi District",
    districtbn: "রাজশাহী",
    coordinates: [24.3733, 88.6049],
  },
  {
    name: "Sirajganj District",
    districtbn: "সিরাজগঞ্জ",
    coordinates: [24.3141, 89.57],
  },
  {
    name: "Dinajpur District",
    districtbn: "দিনাজপুর",
    coordinates: [25.6279, 88.6332],
  },
  {
    name: "Gaibandha District",
    districtbn: "গাইবান্ধা",
    coordinates: [25.3297, 89.543],
  },
  {
    name: "Kurigram District",
    districtbn: "কুড়িগ্রাম",
    coordinates: [25.8072, 89.6295],
  },
  {
    name: "Lalmonirhat District",
    districtbn: "লালমনিরহাট",
    coordinates: [25.9923, 89.2847],
  },
  {
    name: "Nilphamari District",
    districtbn: "নিলফামারী",
    coordinates: [25.8483, 88.9414],
  },
  {
    name: "Panchagarh District",
    districtbn: "পঞ্চগড়",
    coordinates: [26.2709, 88.5952],
  },
  {
    name: "Rangpur District",
    districtbn: "রংপুর",
    coordinates: [25.7468, 89.2508],
  },
  {
    name: "Thakurgaon District",
    districtbn: "ঠাকুরগাঁও",
    coordinates: [26.0418, 88.4283],
  },
  {
    name: "Habiganj District",
    districtbn: "হবিগঞ্জ",
    coordinates: [24.4771, 91.4507],
  },
  {
    name: "Moulvibazar District",
    districtbn: "মৌলভীবাজার",
    coordinates: [24.3095, 91.7315],
  },
  {
    name: "Sunamganj District",
    districtbn: "সুনামগঞ্জ",
    coordinates: [25.0715, 91.3992],
  },
  {
    name: "Sylhet District",
    districtbn: "সিলেট",
    coordinates: [24.8993, 91.87],
  },
];
const division = [
  {
    name: "Barishal Division",
    divisionbn: "বরিশাল",
    coordinates: [22.3811, 90.3372],
  },
  {
    name: "Chattogram Division",
    divisionbn: "চট্টগ্রাম",
    coordinates: [23.1793, 91.9882],
  },
  {
    name: "Dhaka Division",
    divisionbn: "ঢাকা",
    coordinates: [23.9536, 90.1495],
  },
  {
    name: "Khulna Division",
    divisionbn: "খুলনা",
    coordinates: [22.8088, 89.2467],
  },
  {
    name: "Mymensingh Division",
    divisionbn: "ময়মনসিংহ",
    coordinates: [24.7136, 90.4502],
  },
  {
    name: "Rajshahi Division",
    divisionbn: "রাজশাহী",
    coordinates: [24.7106, 88.9414],
  },
  {
    name: "Rangpur Division",
    divisionbn: "রংপুর",
    coordinates: [25.8483, 88.9414],
  },
  {
    name: "Sylhet Division",
    divisionbn: "সিলেট",
    coordinates: [24.705, 91.6761],
  },
];
export { division, district, upazilla };
